export const projects = [
  {
    num: "01",
    category: "frontend",
    title: "Car Website",
    description: "A modern car showcase platform with sleek animations and responsive design.",
    stack: [
      { name: "HTML5" },
      { name: "CSS3" },
      { name: "JavaScript" },
      { name: "Tailwind CSS" },
      { name: "React.js" },
    ],
    level: "😀", // Beginner
    image: "/asset/car.png",
    live: "https://ahmad655656.github.io/Fifth-project/",
    github: "https://github.com/ahmad655656/Fifth-project.git",
  },
  {
    num: "02",
    category: "frontend",
    title: "Games Hub",
    description: "Interactive gaming platform with multiple mini-games and smooth UI.",
    stack: [
      { name: "HTML5" },
      { name: "CSS3" },
      { name: "JavaScript" },
      { name: "Tailwind CSS" },
      { name: "React.js" },
    ],
    level: "😀", // Beginner
    image: "/asset/game.png",
    live: "https://ahmad655656.github.io/gameWebsite/",
    github: "https://github.com/ahmad655656/gameWebsite.git",
  },
  {
    num: "03",
    category: "frontend",
    title: "Portfolio Website",
    description: "Personal portfolio website with creative design and smooth transitions.",
    stack: [
      { name: "HTML5" },
      { name: "CSS3" },
      { name: "JavaScript" },
      { name: "Tailwind CSS" },
      { name: "React.js" },
    ],
    level: "😀", // Beginner
    image: "/asset/portfolio.png",
    live: "https://ahmad655656.github.io/The-fourth-project/",
    github: "https://github.com/ahmad655656/The-fourth-project.git",
  },
  {
    num: "04",
    category: "frontend",
    title: "Medical Platform",
    description: "Healthcare website with appointment booking and medical information.",
    stack: [
      { name: "HTML5" },
      { name: "CSS3" },
      { name: "JavaScript" },
      { name: "Tailwind CSS" },
      { name: "React.js" },
    ],
    level: "😀", // Beginner
    image: "/asset/medical.png",
    live: "",
    github: "https://github.com/ahmad655656/medical.git",
  },
   {
    num: "05",
    category: "full-stack",
    title: "E-Commerce Platform",
    description: "Full-stack e-commerce platform with Stripe integration and admin panel.",
    stack: [
      { name: "HTML5" },
      { name: "CSS3" },
      { name: "JavaScript" },
      { name: "Tailwind CSS" },
      { name: "React.js" },
      { name: "Stripe" },
    ],
    level: "😎", // Intermediate
    image: "/asset/fullstack.mp4",
    live: "https://photoland-five.vercel.app/",
    github: "https://github.com/ahmad655656/photoland.git",
  },
   {
    num: "06",
    category: "frontend",
    title: "CarLand",
    description: "Premium car rental platform with advanced filtering and booking system.",
    stack: [
      { name: "HTML5" },
      { name: "CSS3" },
      { name: "JavaScript" },
      { name: "Tailwind CSS" },
      { name: "React.js" },
      { name: "Next.js" },
    ],
    level: "😎", // Intermediate
    image: "/asset/carland.png",
    live: "https://car-ashy-nine.vercel.app/",
    github: "https://github.com/ahmad655656/car.git",
  },
  {
    num: "07",
    category: "frontend",
    title: "Urban Build",
    description: "Construction company website showcasing projects and services.",
    stack: [
      { name: "HTML5" },
      { name: "CSS3" },
      { name: "JavaScript" },
      { name: "Tailwind CSS" },
      { name: "React.js" },
      { name: "Next.js" },
    ],
    level: "😎", // Intermediate
    image: "/asset/constructions.png",
    live: "https://urban-build-phi.vercel.app/",
    github: "https://github.com/ahmad655656/urbanBuild.git",
  },
  {
    num: "08",
    category: "frontend",
    title: "TypeScript Games",
    description: "Collection of games built with TypeScript for type safety and performance.",
    stack: [
      { name: "HTML5" },
      { name: "CSS3" },
      { name: "TypeScript" },
      { name: "Tailwind CSS" },
      { name: "React.js" },
      { name: "Next.js" },
    ],
    level: "😎", // Intermediate
    image: "/asset/TypeScriptGame.png",
    live: "https://game-chi-ashen-73.vercel.app/",
    github: "https://github.com/ahmad655656/game.git",
  },
  {
    num: "09",
    category: "frontend",
    title: "Software Landing Page",
    description: "Modern software product landing page with conversion optimization.",
    stack: [
      { name: "HTML5" },
      { name: "CSS3" },
      { name: "TypeScript" },
      { name: "Tailwind CSS" },
      { name: "React.js" },
      { name: "Next.js" },
    ],
    level: "😎", // Intermediate
    image: "/asset/softwareLandingPage.png",
    live: "https://software-landing-page-1n9g.vercel.app/",
    github: "https://github.com/ahmad655656/softwareLandingPage.git",
  },
   {
    num: "10",
    category: "frontend",
    title: "AI Image Generator",
    description: "AI-powered image generation platform with DALL-E integration.",
    stack: [
      { name: "HTML5" },
      { name: "CSS3" },
      { name: "TypeScript" },
      { name: "Tailwind CSS" },
      { name: "React.js" },
      { name: "Next.js" },
    ],
    level: "🏆", // Advanced
    image: "/asset/aiImage.png",
    live: "https://ai-image-iota-five.vercel.app/",
    github: "https://github.com/ahmad655656/aiImage.git",
  },
   {
    num: "11",
    category: "frontend",
    title: "Foodie",
    description: "Restaurant discovery platform with reviews and reservation system.",
    stack: [
      { name: "HTML5" },
      { name: "CSS3" },
      { name: "TypeScript" },
      { name: "Tailwind CSS" },
      { name: "React.js" },
      { name: "Next.js" },
    ],
    level: "🏆", // Advanced
    image: "/asset/foodie.png",
    live: "https://foodie-mauve-two.vercel.app",
    github: "https://github.com/ahmad655656/foodie.git",
  },
  {
    num: "12",
    category: "fullstack",
    title: "CodeSync",
    description: "Real-time collaborative coding platform with Clerk authentication.",
    stack: [
      { name: "HTML5" },
      { name: "CSS3" },
      { name: "TypeScript" },
      { name: "Tailwind CSS" },
      { name: "React.js" },
      { name: "Next.js" },
      { name: "Clerk" },
      { name: "Convex" },
    ],
    level: "🏆", // Advanced
    image: "/asset/codesync.png",
    live: "https://condesync.vercel.app/",
    github: "https://github.com/ahmad655656/condesync.git",
  },
  {
    num: "13",
    category: "fullstack",
    title: "Socially",
    description: "Social media platform with real-time updates and Prisma database.",
    stack: [
      { name: "HTML5" },
      { name: "CSS3" },
      { name: "TypeScript" },
      { name: "Tailwind CSS" },
      { name: "React.js" },
      { name: "Next.js" },
      { name: "Clerk" },
      { name: "Prisma" },
    ],
    level: "🏆", // Advanced
    image: "/asset/socially.png",
    live: "https://socially-indol.vercel.app/",
    github: "https://github.com/ahmad655656/socially.git",
  },
  {
    num: "14",
    category: "fullstack",
    title: "SleepTracker",
    description: "Health tracking app with sleep analytics and personalized insights.",
    stack: [
      { name: "HTML5" },
      { name: "CSS3" },
      { name: "TypeScript" },
      { name: "Tailwind CSS" },
      { name: "React.js" },
      { name: "Next.js" },
      { name: "Clerk" },
      { name: "Prisma" },
    ],
    level: "🏆", // Advanced
    image: "/asset/sleeptracker.png",
    live: "https://sleeptracker-rho.vercel.app/",
    github: "https://github.com/ahmad655656/sleeptracker.git",
  },
   {
    num: "15",
    category: "frontend",
    title: "Courses Platform",
    description: "Online learning platform with video courses and progress tracking.",
    stack: [
      { name: "HTML5" },
      { name: "CSS3" },
      { name: "JavaScript" },
      { name: "Tailwind CSS" },
      { name: "React.js" },
      { name: "Next.js" },
    ],
    level: "🏆", // Advanced
    image: "/asset/courses.png",
    live: "https://maiskejani.vercel.app/",
    github: "https://github.com/ahmad655656/maiskejani.git",
  },
  {
    num: "16",
    category: "frontend",
    title: "Intelligence Games",
    description: "Brain training games platform with difficulty progression and scoring.",
    stack: [
      { name: "HTML5" },
      { name: "CSS3" },
      { name: "JavaScript" },
      { name: "Tailwind CSS" },
      { name: "React.js" },
      { name: "Next.js" },
    ],
    level: "🏆", // Advanced
    image: "/asset/IntelligenceGames.png",
    live: "https://gamingapp-one.vercel.app/",
    github: "https://github.com/ahmad655656/gamingapp.git",
  },
];

export const services = [
  {
    num: "01",
    title: "Frontend Development",
    description: "I provide interactive and easy-to-use user interfaces that enhance visitor experience and increase engagement.",
    href: "/contact",
    color: "from-[#8A9A8C] to-[#9BAB9D]",
  },
  {
    num: "02",
    title: "Code Debugging",
    description: "I offer software debugging services to ensure your applications run smoothly and efficiently.",
    href: "/contact",
    color: "from-[#B7AA9A] to-[#C8BBAB]",
  },
  {
    num: "03",
    title: "Logo Design",
    description: "I design unique logos that express your brand identity and leave a lasting impression.",
    href: "/contact",
    color: "from-[#9BAB9D] to-[#8A9A8C]",
  },
  {
    num: "04",
    title: "Video Design",
    description: "I create engaging visual content that reflects your vision and engages your audience professionally.",
    href: "/contact",
    color: "from-[#C8BBAB] to-[#B7AA9A]",
  },
];