// constants/workData.jsx
export const projects = [
  {
    num: "01",
    category: "frontend",
    title: "Car Website",
    description: "A modern car showcase platform with sleek animations and responsive design.",
    stack: ["HTML5", "CSS3", "JavaScript", "Tailwind CSS", "React.js"],
    level: "BEGINNER",
    levelColor: "from-emerald-400 to-cyan-400",
    image: "/asset/car.png",
    live: "https://ahmad655656.github.io/Fifth-project/",
    github: "https://github.com/ahmad655656/Fifth-project.git",
    tech: ["React", "Tailwind"],
  },
  {
    num: "02",
    category: "frontend",
    title: "Games Hub",
    description: "Interactive gaming platform with multiple mini-games and smooth UI.",
    stack: ["HTML5", "CSS3", "JavaScript", "Tailwind CSS", "React.js"],
    level: "BEGINNER",
    levelColor: "from-emerald-400 to-cyan-400",
    image: "/asset/game.png",
    live: "https://ahmad655656.github.io/gameWebsite/",
    github: "https://github.com/ahmad655656/gameWebsite.git",
    tech: ["React", "Tailwind"],
  },
  {
    num: "04",
    category: "frontend",
    title: "Medical Platform",
    description: "Healthcare website with appointment booking and medical information.",
    stack: ["HTML5", "CSS3", "JavaScript", "Tailwind CSS", "React.js"],
    level: "BEGINNER",
    levelColor: "from-emerald-400 to-cyan-400",
    image: "/asset/medical.png",
    live: "",
    github: "https://github.com/ahmad655656/medical.git",
    tech: ["React", "Tailwind"],
  },
  {
    num: "05",
    category: "full-stack",
    title: "E-Commerce",
    description: "Full-stack e-commerce platform with Stripe integration and admin panel.",
    stack: ["HTML5", "CSS3", "JavaScript", "Tailwind CSS", "React.js", "Stripe"],
    level: "INTERMEDIATE",
    levelColor: "from-amber-400 to-orange-400",
    image: "/asset/fullstack.mp4",
    live: "https://photoland-five.vercel.app/",
    github: "https://github.com/ahmad655656/photoland.git",
    tech: ["React", "Next.js", "Stripe"],
  },
  {
    num: "06",
    category: "frontend",
    title: "CarLand",
    description: "Premium car rental platform with advanced filtering and booking system.",
    stack: ["HTML5", "CSS3", "JavaScript", "Tailwind CSS", "React.js", "Next.js"],
    level: "INTERMEDIATE",
    levelColor: "from-amber-400 to-orange-400",
    image: "/asset/carland.png",
    live: "https://car-ashy-nine.vercel.app/",
    github: "https://github.com/ahmad655656/car.git",
    tech: ["Next.js", "Tailwind"],
  },
  {
    num: "07",
    category: "frontend",
    title: "Urban Build",
    description: "Construction company website showcasing projects and services.",
    stack: ["HTML5", "CSS3", "JavaScript", "Tailwind CSS", "React.js", "Next.js"],
    level: "INTERMEDIATE",
    levelColor: "from-amber-400 to-orange-400",
    image: "/asset/constructions.png",
    live: "https://urban-build-phi.vercel.app/",
    github: "https://github.com/ahmad655656/urbanBuild.git",
    tech: ["Next.js", "Tailwind"],
  },
  {
    num: "08",
    category: "frontend",
    title: "TypeScript Games",
    description: "Collection of games built with TypeScript for type safety and performance.",
    stack: ["HTML5", "CSS3", "TypeScript", "Tailwind CSS", "React.js", "Next.js"],
    level: "INTERMEDIATE",
    levelColor: "from-amber-400 to-orange-400",
    image: "/asset/TypeScriptGame.png",
    live: "https://game-chi-ashen-73.vercel.app/",
    github: "https://github.com/ahmad655656/game.git",
    tech: ["Next.js", "TypeScript"],
  },
  {
    num: "09",
    category: "frontend",
    title: "Software Landing",
    description: "Modern software product landing page with conversion optimization.",
    stack: ["HTML5", "CSS3", "TypeScript", "Tailwind CSS", "React.js", "Next.js"],
    level: "INTERMEDIATE",
    levelColor: "from-amber-400 to-orange-400",
    image: "/asset/softwareLandingPage.png",
    live: "https://software-landing-page-1n9g.vercel.app/",
    github: "https://github.com/ahmad655656/softwareLandingPage.git",
    tech: ["Next.js", "TypeScript"],
  },
  {
    num: "10",
    category: "frontend",
    title: "AI Image Generator",
    description: "AI-powered image generation platform with DALL-E integration.",
    stack: ["HTML5", "CSS3", "TypeScript", "Tailwind CSS", "React.js", "Next.js"],
    level: "ADVANCED",
    levelColor: "from-purple-400 to-pink-400",
    image: "/asset/aiImage.png",
    live: "https://ai-image-iota-five.vercel.app/",
    github: "https://github.com/ahmad655656/aiImage.git",
    tech: ["Next.js", "TypeScript", "AI"],
  },
  {
    num: "11",
    category: "frontend",
    title: "Foodie",
    description: "Restaurant discovery platform with reviews and reservation system.",
    stack: ["HTML5", "CSS3", "TypeScript", "Tailwind CSS", "React.js", "Next.js"],
    level: "ADVANCED",
    levelColor: "from-purple-400 to-pink-400",
    image: "/asset/foodie.png",
    live: "https://foodie-mauve-two.vercel.app",
    github: "https://github.com/ahmad655656/foodie.git",
    tech: ["Next.js", "TypeScript"],
  },
  {
    num: "12",
    category: "fullstack",
    title: "CodeSync",
    description: "Real-time collaborative coding platform with Clerk authentication.",
    stack: ["HTML5", "CSS3", "TypeScript", "Tailwind CSS", "React.js", "Next.js", "Clerk", "Convex"],
    level: "ADVANCED",
    levelColor: "from-purple-400 to-pink-400",
    image: "/asset/codesync.png",
    live: "https://condesync.vercel.app/",
    github: "https://github.com/ahmad655656/condesync.git",
    tech: ["Next.js", "TypeScript", "Realtime"],
  },
  {
    num: "13",
    category: "fullstack",
    title: "Socially",
    description: "Social media platform with real-time updates and Prisma database.",
    stack: ["HTML5", "CSS3", "TypeScript", "Tailwind CSS", "React.js", "Next.js", "Clerk", "Prisma"],
    level: "ADVANCED",
    levelColor: "from-purple-400 to-pink-400",
    image: "/asset/socially.png",
    live: "https://socially-indol.vercel.app/",
    github: "https://github.com/ahmad655656/socially.git",
    tech: ["Next.js", "TypeScript", "Prisma"],
  },
  {
    num: "14",
    category: "fullstack",
    title: "SleepTracker",
    description: "Health tracking app with sleep analytics and personalized insights.",
    stack: ["HTML5", "CSS3", "TypeScript", "Tailwind CSS", "React.js", "Next.js", "Clerk", "Prisma"],
    level: "ADVANCED",
    levelColor: "from-purple-400 to-pink-400",
    image: "/asset/sleeptracker.png",
    live: "https://sleeptracker-rho.vercel.app/",
    github: "https://github.com/ahmad655656/sleeptracker.git",
    tech: ["Next.js", "TypeScript", "Prisma"],
  },
  {
    num: "15",
    category: "frontend",
    title: "Courses Platform",
    description: "Online learning platform with video courses and progress tracking.",
    stack: ["HTML5", "CSS3", "JavaScript", "Tailwind CSS", "React.js", "Next.js"],
    level: "ADVANCED",
    levelColor: "from-purple-400 to-pink-400",
    image: "/asset/courses.png",
    live: "https://maiskejani.vercel.app/",
    github: "https://github.com/ahmad655656/maiskejani.git",
    tech: ["Next.js", "Tailwind"],
  },
  {
    num: "16",
    category: "frontend",
    title: "Intelligence Games",
    description: "Brain training games platform with difficulty progression and scoring.",
    stack: ["HTML5", "CSS3", "JavaScript", "Tailwind CSS", "React.js", "Next.js"],
    level: "ADVANCED",
    levelColor: "from-purple-400 to-pink-400",
    image: "/asset/IntelligenceGames.png",
    live: "https://gamingapp-one.vercel.app/",
    github: "https://github.com/ahmad655656/gamingapp.git",
    tech: ["Next.js", "Tailwind"],
  },
  {
    num: "17",
    category: "fullstack",
    title: "Car Rental Platform",
    description: "Integrated car booking platform with complete management system, user authentication, and instant reservations.",
    longDescription: "A comprehensive car rental platform that allows users to search for available cars, book them, and manage their reservations. Includes an admin dashboard for managing cars, bookings, and users.",
    stack: ["Next.js", "TypeScript", "MongoDB", "Tailwind CSS", "NextAuth", "Mongoose"],
    level: "ADVANCED",
    levelColor: "from-purple-400 to-pink-400",
    image: "/asset/company-cars.png",
    live: "https://company-cars.vercel.app",
    github: "https://github.com/ahmad655656/companyCars.git",
    tech: ["Next.js", "TypeScript", "MongoDB", "NextAuth"],
    features: [
      "Advanced car search",
      "Instant booking system",
      "Admin dashboard",
      "User authentication",
      "Profile management",
      "Filter by price and model",
    ]
  },
];

export const stats = [
  { value: "16+", label: "Total Projects" },
  { value: "5+", label: "Full Stack" },
  { value: "11+", label: "Frontend" },
  { value: "6+", label: "Advanced" },
];