export const projects = [
  // Intermediate Level
  {
    num: "01",
    category: "frontend",
    title: "CarLand",
    description: "Premium car rental platform with advanced filtering and booking system.",
    stack: ["HTML5", "CSS3", "JavaScript", "Tailwind CSS", "React.js", "Next.js"],
    level: "INTERMEDIATE",
    levelColor: "from-amber-400 to-orange-400",
    image: "/asset/carland.png",
    live: "https://car-ashy-nine.vercel.app/",
    github: "https://github.com/ahmad655656/car.git",
    tech: ["Next.js", "Tailwind"],
  },
  {
    num: "02",
    category: "frontend",
    title: "Urban Build",
    description: "Construction company website showcasing projects and services.",
    stack: ["HTML5", "CSS3", "JavaScript", "Tailwind CSS", "React.js", "Next.js"],
    level: "INTERMEDIATE",
    levelColor: "from-amber-400 to-orange-400",
    image: "/asset/constructions.png",
    live: "https://urban-build-phi.vercel.app/",
    github: "https://github.com/ahmad655656/urbanBuild.git",
    tech: ["Next.js", "Tailwind"],
  },
  {
    num: "03",
    category: "frontend",
    title: "TypeScript Games",
    description: "Collection of games built with TypeScript for type safety and performance.",
    stack: ["HTML5", "CSS3", "TypeScript", "Tailwind CSS", "React.js", "Next.js"],
    level: "INTERMEDIATE",
    levelColor: "from-amber-400 to-orange-400",
    image: "/asset/TypeScriptGame.png",
    live: "https://game-chi-ashen-73.vercel.app/",
    github: "https://github.com/ahmad655656/game.git",
    tech: ["Next.js", "TypeScript"],
  },
  {
    num: "04",
    category: "frontend",
    title: "Software Landing",
    description: "Modern software product landing page with conversion optimization.",
    stack: ["HTML5", "CSS3", "TypeScript", "Tailwind CSS", "React.js", "Next.js"],
    level: "INTERMEDIATE",
    levelColor: "from-amber-400 to-orange-400",
    image: "/asset/softwareLandingPage.png",
    live: "https://software-landing-page-1n9g.vercel.app/",
    github: "https://github.com/ahmad655656/softwareLandingPage.git",
    tech: ["Next.js", "TypeScript"],
  },

  // Advanced Level
  {
    num: "05",
    category: "frontend",
    title: "AI Image Generator",
    description: "AI-powered image generation platform with DALL-E integration.",
    stack: ["HTML5", "CSS3", "TypeScript", "Tailwind CSS", "React.js", "Next.js"],
    level: "ADVANCED",
    levelColor: "from-purple-400 to-pink-400",
    image: "/asset/aiImage.png",
    live: "https://ai-image-iota-five.vercel.app/",
    github: "https://github.com/ahmad655656/aiImage.git",
    tech: ["Next.js", "TypeScript", "AI"],
  },
  {
    num: "06",
    category: "frontend",
    title: "Foodie",
    description: "Restaurant discovery platform with reviews and reservation system.",
    stack: ["HTML5", "CSS3", "TypeScript", "Tailwind CSS", "React.js", "Next.js"],
    level: "ADVANCED",
    levelColor: "from-purple-400 to-pink-400",
    image: "/asset/foodie.png",
    live: "https://foodie-mauve-two.vercel.app",
    github: "https://github.com/ahmad655656/foodie.git",
    tech: ["Next.js", "TypeScript"],
  },
  {
    num: "07",
    category: "frontend",
    title: "Courses Platform",
    description: "Online learning platform with video courses and progress tracking.",
    stack: ["HTML5", "CSS3", "JavaScript", "Tailwind CSS", "React.js", "Next.js"],
    level: "ADVANCED",
    levelColor: "from-purple-400 to-pink-400",
    image: "/asset/courses.png",
    live: "https://maiskejani.vercel.app/",
    github: "https://github.com/ahmad655656/maiskejani.git",
    tech: ["Next.js", "Tailwind"],
  },
  {
    num: "08",
    category: "frontend",
    title: "Intelligence Games",
    description: "Brain training games platform with difficulty progression and scoring.",
    stack: ["HTML5", "CSS3", "JavaScript", "Tailwind CSS", "React.js", "Next.js"],
    level: "ADVANCED",
    levelColor: "from-purple-400 to-pink-400",
    image: "/asset/IntelligenceGames.png",
    live: "https://gamingapp-one.vercel.app/",
    github: "https://github.com/ahmad655656/gamingapp.git",
    tech: ["Next.js", "Tailwind"],
  },
  {
    num: "09",
    category: "frontend",
    title: "Virtual Museum - 360° Tours",
    description: "Interactive virtual museum platform with 360° immersive tours, interactive maps, and cultural heritage exploration across 9 countries.",
    longDescription: "A revolutionary digital platform that takes users on an immersive journey through world heritage sites. Features 360° panoramic views, interactive maps with real landmarks, category-based exploration (Historical, Natural, Modern, Maritime), and detailed historical information about 13+ international landmarks across 9 countries.",
    stack: ["Next.js 14", "TypeScript", "Tailwind CSS", "Leaflet", "React Leaflet", "AirPano API", "Framer Motion"],
    level: "ADVANCED",
    levelColor: "from-purple-400 to-pink-400",
    image: "/asset/virtual.png",
    live: "https://virtual-tour-delta.vercel.app/",
    github: "https://github.com/ahmad655656/virtualTour.git",
    tech: ["Next.js 14", "TypeScript", "Tailwind", "Leaflet", "Framer Motion"],
    features: [
      "360° immersive virtual tours",
      "Interactive world map with landmark markers",
      "Category-based filtering (Historical, Natural, Modern, Maritime)",
      "Responsive design for all devices",
      "Detailed landmark pages with historical context",
      "Real-time map interactions",
      "Cultural heritage preservation",
      "Multi-language support (Arabic/English)",
      "Advanced animations and transitions",
      "Dynamic routing for each landmark",
      "Server-side rendering for SEO optimization"
    ],
    highlights: [
      "13+ international landmarks",
      "9 countries represented",
      "4 distinct categories",
      "Real AirPano 360° integrations"
    ]
  },

  // ========== FULLSTACK PROJECTS ==========
  {
    num: "10",
    category: "fullstack",
    title: "Socially",
    description: "Social media platform with real-time updates and Prisma database.",
    stack: ["HTML5", "CSS3", "TypeScript", "Tailwind CSS", "React.js", "Next.js", "Clerk", "Prisma"],
    level: "ADVANCED",
    levelColor: "from-purple-400 to-pink-400",
    image: "/asset/socially.png",
    live: "https://socially-indol.vercel.app/",
    github: "https://github.com/ahmad655656/socially.git",
    tech: ["Next.js", "TypeScript", "Prisma"],
  },
  {
    num: "11",
    category: "fullstack",
    title: "SleepTracker",
    description: "Health tracking app with sleep analytics and personalized insights.",
    stack: ["HTML5", "CSS3", "TypeScript", "Tailwind CSS", "React.js", "Next.js", "Clerk", "Prisma"],
    level: "ADVANCED",
    levelColor: "from-purple-400 to-pink-400",
    image: "/asset/Sleep.png",
    live: "https://sleeptracker-rho.vercel.app/",
    github: "https://github.com/ahmad655656/sleeptracker.git",
    tech: ["Next.js", "TypeScript", "Prisma"],
  },
  {
    num: "12",
    category: "fullstack",
    title: "Car Rental Platform",
    description: "Integrated car booking platform with complete management system, user authentication, and instant reservations.",
    longDescription: "A comprehensive car rental platform that allows users to search for available cars, book them, and manage their reservations. Includes an admin dashboard for managing cars, bookings, and users.",
    stack: ["Next.js", "TypeScript", "MongoDB", "Tailwind CSS", "NextAuth", "Mongoose"],
    level: "ADVANCED",
    levelColor: "from-purple-400 to-pink-400",
    image: "/asset/company-cars.png",
    live: "https://company-cars.vercel.app",
    github: "https://github.com/ahmad655656/companyCars.git",
    tech: ["Next.js", "TypeScript", "MongoDB", "NextAuth"],
    features: [
      "Advanced car search",
      "Instant booking system",
      "Admin dashboard",
      "User authentication",
      "Profile management",
      "Filter by price and model",
    ]
  },
];

export const stats = [
  { 
    value: "12+", 
    label: "Total Projects",
    icon: "🚀",
    color: "from-amber-500/20 to-orange-500/20"
  },
  { 
    value: "3+", 
    label: "Full Stack",
    icon: "⚙️",
    color: "from-blue-500/20 to-cyan-500/20"
  },
  { 
    value: "09+", 
    label: "Frontend",
    icon: "🎨",
    color: "from-purple-500/20 to-pink-500/20"
  },
  { 
    value: "8+", 
    label: "Advanced Level",
    icon: "🔥",
    color: "from-emerald-500/20 to-green-500/20"
  },
];